/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageFlight;
import Business.Airliner.Airliner;
import Business.Customer.Customer;
import Business.Schedule.Flight;
import Business.Schedule.FlightSchedule;
import Business.TravelAgency;
import java.awt.CardLayout;
import UserInterface.MainJFrame;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author apple
 */
public class ManageFlightJPanel extends javax.swing.JPanel {
    private JPanel rightPanel;  
    private FlightSchedule flightSchedule;
    private Airliner airliner;
    private TravelAgency travelAgency;
    /**
     * Creates new form ManageFlightJPanel
     */
    public ManageFlightJPanel(JPanel rightPanel, Airliner airliner, TravelAgency travelAgency) {
        initComponents();
        this.rightPanel = rightPanel;
        this.airliner = airliner;
        this.travelAgency = travelAgency;
        this.flightSchedule = airliner.getFlightSchedule();
        populateTable();
    }
    
    private void populateTable(){
        
        DefaultTableModel dtm = (DefaultTableModel) tblFlight.getModel();
        dtm.setRowCount(0);
        if(flightSchedule!=null){
        for(Flight flight: flightSchedule.getFlightList()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = flight;   
            row[1] = flight.getAirplane();
            row[2] = flight.getFrom();
            row[3] = flight.getTo();
            Date date = flight.getDepartureTime();  
            DateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy HH:mm:ss");  
            String strDate = dateFormat.format(date);
            row[4] = strDate;
            Date date2 = flight.getArrivalTime();  
            DateFormat dateFormat2 = new SimpleDateFormat("dd-MMM-yyyy HH:mm:ss");  
            String strDate2 = dateFormat2.format(date2);
            row[5] = strDate2;
            row[6] = flight.getTimeSlot();
            dtm.addRow(row);    
        }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlight = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblFlight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FlightNum", "Airplane", "From", "To", "Departure Time", "Arrival Time", "Time Slot"
            }
        ));
        jScrollPane1.setViewportView(tblFlight);
        if (tblFlight.getColumnModel().getColumnCount() > 0) {
            tblFlight.getColumnModel().getColumn(1).setMinWidth(80);
            tblFlight.getColumnModel().getColumn(2).setMaxWidth(50);
            tblFlight.getColumnModel().getColumn(3).setMaxWidth(50);
            tblFlight.getColumnModel().getColumn(4).setMinWidth(100);
            tblFlight.getColumnModel().getColumn(5).setMinWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 200));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 80, -1));

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Flight List");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        btnRefresh.setText("refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 0, 710, 288));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CreateFlightJPanel panel = new CreateFlightJPanel(rightPanel,flightSchedule,travelAgency);
        rightPanel.add("CreateFlightJPanel",panel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblFlight .getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row of the first table to view details.","Warning",JOptionPane.WARNING_MESSAGE);
        }else{
            //Flight flight = flightSchedule.searchName((String) tblFlight.getValueAt(selectedRow,1));
            Flight flight = (Flight) tblFlight.getValueAt(selectedRow,0);
            ViewFlightJPanel panel = new ViewFlightJPanel(rightPanel,flight,airliner,travelAgency);
            rightPanel.add("ViewFlightJPanel",panel);
            CardLayout layout = (CardLayout) rightPanel.getLayout();
            layout.next(rightPanel);}
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblFlight.getSelectedRow();
        if(selectedRow >=0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null,"Would your like to delete this infomation?","Warning",JOptionPane.WARNING_MESSAGE);
            if(dialogResult == JOptionPane.YES_NO_OPTION){
                Flight flight = (Flight) tblFlight.getValueAt(selectedRow,0);
                if(!travelAgency.getTravelOffice().getCustomerDirectory().getCustomerList().isEmpty()){
                    for(Customer c : travelAgency.getTravelOffice().getCustomerDirectory().getCustomerList()){
                      c.deleteFlight(flight);
                    }
                }
                flightSchedule.deleteFlight(flight);
                if(flightSchedule.getFlightList().isEmpty()){
                      travelAgency.getMasterFlightSchedule().getFlightScheduleList().remove(flightSchedule);
                }
                populateTable();
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select a row from table first.","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFlight;
    // End of variables declaration//GEN-END:variables
}
