/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomer;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.Customer.Ticket;
import Business.Schedule.Flight;
import Business.Schedule.FlightSchedule;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apple
 */
public class ViewCustomerJPanel extends javax.swing.JPanel {
     private JPanel rightPanel;
    private Customer customer;
    private CustomerDirectory customerDir; 
    private FlightSchedule flightSchedule;

    /**
     * Creates new form ViewCustomerJPanel
     */
    public ViewCustomerJPanel(JPanel rightPanel,Customer customer) {
        initComponents();
        this.rightPanel = rightPanel;
        this.customer= customer;
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewCustomer = new javax.swing.JTable();
        btnDeleteFlight = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("View Customer Flight");

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblViewCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight", "Departure Time", "Arrival Time", "Time Slot", "From", "To", "Seat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewCustomer);
        if (tblViewCustomer.getColumnModel().getColumnCount() > 0) {
            tblViewCustomer.getColumnModel().getColumn(1).setMinWidth(100);
            tblViewCustomer.getColumnModel().getColumn(2).setMinWidth(100);
            tblViewCustomer.getColumnModel().getColumn(3).setMaxWidth(80);
            tblViewCustomer.getColumnModel().getColumn(4).setMaxWidth(50);
            tblViewCustomer.getColumnModel().getColumn(5).setMaxWidth(50);
            tblViewCustomer.getColumnModel().getColumn(6).setMaxWidth(50);
        }

        btnDeleteFlight.setText("Delete");
        btnDeleteFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFlightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                    .addComponent(btnDeleteFlight))
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnBack)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnDeleteFlight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);    
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void populate(){
         DefaultTableModel dtm = (DefaultTableModel) tblViewCustomer.getModel();
         dtm.setRowCount(0);
        
            for(Ticket t : customer.getTicketList()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = t; 
            Date date = t.getFlight().getDepartureTime();  
            DateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy HH:mm:ss");  
            String strDate = dateFormat.format(date);
            row[1] = strDate;
            Date date2 = t.getFlight().getArrivalTime();  
            DateFormat dateFormat2 = new SimpleDateFormat("dd-MMM-yyyy HH:mm:ss");  
            String strDate2 = dateFormat2.format(date2);
            row[2] = strDate2;
            row[3] = t.getFlight().getTimeSlot();
            row[4] = t.getFlight().getFrom();
            row[5] = t.getFlight().getTo();
            row[6] = t.getSeat();
            dtm.addRow(row);    
           
        }
    }
    
    private void btnDeleteFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFlightActionPerformed
        // TODO add your handling code here:  
        int selectedRow = tblViewCustomer.getSelectedRow();
        if(selectedRow >=0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null,"Would your like to delete the flight?","Warning",JOptionPane.WARNING_MESSAGE);
            if(dialogResult == JOptionPane.YES_NO_OPTION){
                Ticket t = (Ticket) tblViewCustomer.getValueAt(selectedRow,0);
                //flightSchedule.deleteFlight(flight);
                customer.deleteTicket(t);
                populate();
            }
        }
        else{
             JOptionPane.showMessageDialog(null,"Please select a row from table first.","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
          
    }//GEN-LAST:event_btnDeleteFlightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteFlight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViewCustomer;
    // End of variables declaration//GEN-END:variables
}
